//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderlines = new HashSet<Orderline>();
        }
    
        public int Id { get; set; }
        public string OrderNr { get; set; }
        public string Description { get; set; }
        public int SessionId { get; set; }
        public int TableId { get; set; }
        public string OrderStatus { get; set; }
        public string OrderType { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<double> Deposit { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public int Discount { get; set; }
        public double TotalLines { get; set; }
        public double TotalOrder { get; set; }
        public bool IsPrinted { get; set; }
        public double ServiceCost { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual TablePos TablePos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderline> Orderlines { get; set; }
    }
}
