//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamvietSender.NamvietApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://namvietkhanhhoa.com/SOAP/DoanhThu", ConfigurationName="NamvietApi.Namviet")]
    public interface Namviet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namvietkhanhhoa.com/SOAP/DoanhThu/Namviet/DoWork", ReplyAction="http://namvietkhanhhoa.com/SOAP/DoanhThu/Namviet/DoWorkResponse")]
        void DoWork(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namvietkhanhhoa.com/SOAP/DoanhThu/Namviet/DoWork", ReplyAction="http://namvietkhanhhoa.com/SOAP/DoanhThu/Namviet/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NamvietChannel : NamvietSender.NamvietApi.Namviet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NamvietClient : System.ServiceModel.ClientBase<NamvietSender.NamvietApi.Namviet>, NamvietSender.NamvietApi.Namviet {
        
        public NamvietClient() {
        }
        
        public NamvietClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NamvietClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamvietClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamvietClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork(string data) {
            base.Channel.DoWork(data);
        }
        
        public System.Threading.Tasks.Task DoWorkAsync(string data) {
            return base.Channel.DoWorkAsync(data);
        }
    }
}
