//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namviet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Id { get; set; }
        public int ExternalId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Price { get; set; }
        public double Amount { get; set; }
    }
}
