//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLink
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string PostLinkType { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public string SmallOverviewContent { get; set; }
        public int Position { get; set; }
        public bool IsActive { get; set; }
        public bool IsHomeShowed { get; set; }
    }
}
