//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosUser
    {
        public int Id { get; set; }
        public string UniqueId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeviceUuid { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> FirstLoginDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsError { get; set; }
    }
}
