//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public int ProductTypeGroupId { get; set; }
        public bool IsActive { get; set; }
        public bool IsHomeShowed { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ProductTypeGroup ProductTypeGroup { get; set; }
        public virtual ProductTypeGroup ProductTypeGroup1 { get; set; }
    }
}
