//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public int ProductTypeGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PriceVnd { get; set; }
        public bool IsActive { get; set; }
        public bool IsHomeShowed { get; set; }
        public string ImageUrl { get; set; }
        public bool IsSaleOff { get; set; }
        public bool IsHot { get; set; }
        public string Note { get; set; }
        public string Warranty { get; set; }
        public int Position { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ProductTypeGroup ProductTypeGroup { get; set; }
        public virtual ProductType ProductType1 { get; set; }
        public virtual ProductTypeGroup ProductTypeGroup1 { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
