//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDailyline
    {
        public int Id { get; set; }
        public int DailyId { get; set; }
        public string ProductNo { get; set; }
        public string ProductName { get; set; }
        public string ProductGroup { get; set; }
        public double Amout { get; set; }
        public double Price { get; set; }
        public string Om { get; set; }
    
        public virtual ReportDaily ReportDaily { get; set; }
    }
}
