//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUser
    {
        public RUser()
        {
            this.ReportDailies = new HashSet<ReportDaily>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public bool IsActive { get; set; }
        public string AccessToken { get; set; }
        public bool IsOnline { get; set; }
    
        public virtual ICollection<ReportDaily> ReportDailies { get; set; }
    }
}
