//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanct.Dal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VanctEntities : DbContext
    {
        public VanctEntities()
            : base("name=VanctEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseFile> BaseFiles { get; set; }
        public virtual DbSet<BaseUser> BaseUsers { get; set; }
        public virtual DbSet<HomeGallery> HomeGalleries { get; set; }
        public virtual DbSet<OpenIdConfig> OpenIdConfigs { get; set; }
        public virtual DbSet<PosCompany> PosCompanies { get; set; }
        public virtual DbSet<PostLink> PostLinks { get; set; }
        public virtual DbSet<PostLinkType> PostLinkTypes { get; set; }
        public virtual DbSet<PosUser> PosUsers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ProductTypeGroup> ProductTypeGroups { get; set; }
        public virtual DbSet<ReportDaily> ReportDailies { get; set; }
        public virtual DbSet<ReportDailyline> ReportDailylines { get; set; }
        public virtual DbSet<RUser> RUsers { get; set; }
        public virtual DbSet<SupportOnline> SupportOnlines { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
